In [2726]:
import sys

import sklearn
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2727]:
test = pd.read_csv('test.csv', index_col=['Id'])

In [2728]:
train = pd.read_csv('train.csv', index_col=['Id'])
train.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal',
       'MoSold', 'YrSold', 'SaleType', 'SaleCondition', 'SalePrice'],
      dtype='object')

In [2729]:
train.MSSubClass.value_counts()

20     536
60     299
50     144
120     87
30      69
160     63
70      60
80      58
90      52
190     30
85      20
75      16
45      12
180     10
40       4
Name: MSSubClass, dtype: int64

In [2730]:
train.MSZoning.value_counts()

RL         1151
RM          218
FV           65
RH           16
C (all)      10
Name: MSZoning, dtype: int64

In [2731]:
test.MSSubClass.value_counts()

20     543
60     276
50     143
120     95
30      70
70      68
160     65
80      60
90      57
190     31
85      28
180      7
75       7
45       6
40       2
150      1
Name: MSSubClass, dtype: int64

MSSubclass in test set has one sample with 1-1/2 STORY PUD - ALL AGES while train set has no such sample

In [2732]:
train.LotFrontage.value_counts()

60.0     143
70.0      70
80.0      69
50.0      57
75.0      53
65.0      44
85.0      40
78.0      25
21.0      23
90.0      23
68.0      19
24.0      19
64.0      19
73.0      18
72.0      17
79.0      17
63.0      17
55.0      17
100.0     16
51.0      15
66.0      15
74.0      15
52.0      14
59.0      13
71.0      12
82.0      12
40.0      12
43.0      12
67.0      12
57.0      12
        ...
129.0      2
124.0      2
118.0      2
101.0      2
122.0      2
121.0      2
115.0      2
109.0      2
116.0      2
114.0      2
150.0      1
111.0      1
153.0      1
182.0      1
46.0       1
112.0      1
149.0      1
141.0      1
33.0       1
152.0      1
160.0      1
168.0      1
128.0      1
144.0      1
39.0       1
106.0      1
38.0       1
138.0      1
140.0      1
137.0      1
Name: LotFrontage, Length: 110, dtype: int64

In [2733]:
test.LotArea.value_counts()

9600     20
7200     18
6000     17
9000     15
7500     12
10800    11
6240     10
7000      9
6120      9
1680      8
9750      7
8000      7
8400      7
10320     7
8640      6
2280      6
10400     6
9350      5
11050     5
5400      5
9900      5
8750      5
8250      4
10200     4
9100      4
5000      4
8064      4
1890      4
8125      4
10000     4
         ..
22002     1
9510      1
12778     1
9488      1
6490      1
9556      1
9555      1
13650     1
9547      1
13641     1
9543      1
9576      1
7488      1
9533      1
15676     1
4590      1
11578     1
11577     1
7480      1
7476      1
13618     1
9520      1
13615     1
6488      1
15660     1
9638      1
9545      1
11563     1
13607     1
12291     1
Name: LotArea, Length: 1106, dtype: int64

Could  delete this column

In [2734]:
train.Street.value_counts()

Pave    1454
Grvl       6
Name: Street, dtype: int64

In [2735]:
test.Street.value_counts()

Pave    1453
Grvl       6
Name: Street, dtype: int64

In [2736]:
train.Alley.value_counts()

Grvl    50
Pave    41
Name: Alley, dtype: int64

In [2737]:
train.LotShape.value_counts()

Reg    925
IR1    484
IR2     41
IR3     10
Name: LotShape, dtype: int64

In [2738]:
train.LandContour.value_counts()

Lvl    1311
Bnk      63
HLS      50
Low      36
Name: LandContour, dtype: int64

Should delete this column

In [2739]:
train.Utilities.value_counts()

AllPub    1459
NoSeWa       1
Name: Utilities, dtype: int64

In [2740]:
train.LotConfig.value_counts()

Inside     1052
Corner      263
CulDSac      94
FR2          47
FR3           4
Name: LotConfig, dtype: int64

In [2741]:
train.LandSlope.value_counts()

Gtl    1382
Mod      65
Sev      13
Name: LandSlope, dtype: int64

In [2742]:
train.LandSlope.isna().sum()

0

In [2743]:
train.Neighborhood.value_counts()

NAmes      225
CollgCr    150
OldTown    113
Edwards    100
Somerst     86
Gilbert     79
NridgHt     77
Sawyer      74
NWAmes      73
SawyerW     59
BrkSide     58
Crawfor     51
Mitchel     49
NoRidge     41
Timber      38
IDOTRR      37
ClearCr     28
SWISU       25
StoneBr     25
Blmngtn     17
MeadowV     17
BrDale      16
Veenker     11
NPkVill      9
Blueste      2
Name: Neighborhood, dtype: int64

In [2744]:
train.Condition1.value_counts()

Norm      1260
Feedr       81
Artery      48
RRAn        26
PosN        19
RRAe        11
PosA         8
RRNn         5
RRNe         2
Name: Condition1, dtype: int64

In [2745]:
train.Condition2.value_counts()

Norm      1445
Feedr        6
Artery       2
RRNn         2
PosN         2
RRAe         1
RRAn         1
PosA         1
Name: Condition2, dtype: int64

In [2746]:
train.BldgType.value_counts()

1Fam      1220
TwnhsE     114
Duplex      52
Twnhs       43
2fmCon      31
Name: BldgType, dtype: int64

In [2747]:
train.BldgType.values

array(['1Fam', '1Fam', '1Fam', ..., '1Fam', '1Fam', '1Fam'], dtype=object)

In [2748]:
train.HouseStyle.value_counts()

1Story    726
2Story    445
1.5Fin    154
SLvl       65
SFoyer     37
1.5Unf     14
2.5Unf     11
2.5Fin      8
Name: HouseStyle, dtype: int64

In [2749]:
train.OverallQual.value_counts()

5     397
6     374
7     319
8     168
4     116
9      43
3      20
10     18
2       3
1       2
Name: OverallQual, dtype: int64

In [2750]:
train.OverallCond.value_counts()

5    821
6    252
7    205
8     72
4     57
3     25
9     22
2      5
1      1
Name: OverallCond, dtype: int64

In [2751]:
train.YearBuilt.value_counts()

2006    67
2005    64
2004    54
2007    49
2003    45
1976    33
1977    32
1920    30
1959    26
1999    25
1998    25
1958    24
1965    24
1970    24
1954    24
2000    24
2002    23
2008    23
1972    23
1968    22
1971    22
1950    20
2001    20
1957    20
1962    19
1994    19
1966    18
2009    18
1995    18
1940    18
        ..
1986     5
1952     5
1880     4
1929     4
1932     4
1938     4
1983     4
1927     3
1919     3
1934     3
1989     3
1987     3
1912     3
1885     2
1892     2
1890     2
1942     2
1908     2
1882     1
1875     1
1893     1
2010     1
1898     1
1904     1
1905     1
1906     1
1911     1
1913     1
1917     1
1872     1
Name: YearBuilt, Length: 112, dtype: int64

In [2752]:
train.YearRemodAdd.value_counts()

1950    178
2006     97
2007     76
2005     73
2004     62
2000     55
2003     51
2002     48
2008     40
1996     36
1998     36
1995     31
1976     30
1999     30
1970     26
1997     25
1977     25
2009     23
1994     22
2001     21
1972     20
1965     19
1993     19
1971     18
1959     18
1968     17
1992     17
1978     16
1966     15
1958     15
       ...
1962     14
1954     14
1969     14
1991     14
1963     13
1960     12
1967     12
1980     12
1973     11
1964     11
1989     11
1987     10
1975     10
1979     10
1956     10
1953     10
1957      9
1988      9
1955      9
1985      9
1961      8
1981      8
1974      7
1982      7
1984      7
2010      6
1983      5
1952      5
1986      5
1951      4
Name: YearRemodAdd, Length: 61, dtype: int64

In [2753]:
train.RoofStyle.value_counts()

Gable      1141
Hip         286
Flat         13
Gambrel      11
Mansard       7
Shed          2
Name: RoofStyle, dtype: int64

In [2754]:
train.RoofStyle.count()

1460

Exterior1st has 15 values in train set while the description has 17 values

In [2755]:
train.Exterior1st.value_counts()

VinylSd    515
HdBoard    222
MetalSd    220
Wd Sdng    206
Plywood    108
CemntBd     61
BrkFace     50
WdShing     26
Stucco      25
AsbShng     20
Stone        2
BrkComm      2
AsphShn      1
CBlock       1
ImStucc      1
Name: Exterior1st, dtype: int64

In [2756]:
train.Exterior2nd.value_counts()

VinylSd    504
MetalSd    214
HdBoard    207
Wd Sdng    197
Plywood    142
CmentBd     60
Wd Shng     38
Stucco      26
BrkFace     25
AsbShng     20
ImStucc     10
Brk Cmn      7
Stone        5
AsphShn      3
CBlock       1
Other        1
Name: Exterior2nd, dtype: int64

In [2757]:
train.MasVnrType.value_counts()

None       864
BrkFace    445
Stone      128
BrkCmn      15
Name: MasVnrType, dtype: int64

In [2758]:
train.MasVnrArea.value_counts()

0.0       861
72.0        8
180.0       8
108.0       8
120.0       7
16.0        7
80.0        6
200.0       6
106.0       6
340.0       6
170.0       5
132.0       5
360.0       5
84.0        5
320.0       5
100.0       4
196.0       4
246.0       4
216.0       4
160.0       4
183.0       4
178.0       4
270.0       4
300.0       4
210.0       4
268.0       4
252.0       4
168.0       4
336.0       4
220.0       4
         ...
14.0        1
53.0        1
24.0        1
127.0       1
365.0       1
115.0       1
562.0       1
259.0       1
378.0       1
219.0       1
161.0       1
247.0       1
109.0       1
278.0       1
375.0       1
225.0       1
604.0       1
762.0       1
290.0       1
299.0       1
202.0       1
731.0       1
167.0       1
309.0       1
1129.0      1
651.0       1
337.0       1
415.0       1
293.0       1
621.0       1
Name: MasVnrArea, Length: 327, dtype: int64

In [2759]:
train.ExterQual.value_counts()

TA    906
Gd    488
Ex     52
Fa     14
Name: ExterQual, dtype: int64

In [2760]:
train.ExterCond.value_counts()

TA    1282
Gd     146
Fa      28
Ex       3
Po       1
Name: ExterCond, dtype: int64

In [2761]:
train.Foundation.value_counts()

PConc     647
CBlock    634
BrkTil    146
Slab       24
Stone       6
Wood        3
Name: Foundation, dtype: int64

In [2762]:
train.BsmtCond.value_counts()

TA    1311
Gd      65
Fa      45
Po       2
Name: BsmtCond, dtype: int64

In [2763]:
train.BsmtExposure.value_counts()

No    953
Av    221
Gd    134
Mn    114
Name: BsmtExposure, dtype: int64

In [2764]:
train.BsmtFinType1.value_counts()

Unf    430
GLQ    418
ALQ    220
BLQ    148
Rec    133
LwQ     74
Name: BsmtFinType1, dtype: int64

In [2765]:
train.BsmtFinType1.count()

1423

In [2766]:
train.BsmtFinSF1.count()

1460

Maybe BsmtFinSF2 should be deleted

In [2767]:
train.BsmtFinSF2.value_counts()

0       1293
180        5
374        3
551        2
93         2
468        2
147        2
480        2
539        2
712        2
117        2
279        2
96         2
391        2
287        2
290        2
294        2
64         2
41         2
182        2
469        2
228        1
208        1
210        1
211        1
202        1
215        1
193        1
219        1
184        1
        ...
354        1
1080       1
1127       1
375        1
377        1
380        1
396        1
400        1
411        1
420        1
435        1
438        1
441        1
465        1
466        1
472        1
479        1
486        1
491        1
492        1
495        1
499        1
500        1
506        1
531        1
532        1
544        1
546        1
547        1
1474       1
Name: BsmtFinSF2, Length: 144, dtype: int64

In [2768]:
train.TotalBsmtSF.value_counts()

0       37
864     35
672     17
912     15
1040    14
816     13
728     12
768     12
848     11
780     11
894     11
832     10
630      9
756      9
952      9
1056     8
936      8
1008     7
483      7
840      7
384      7
720      7
600      7
1362     6
876      6
858      6
884      6
1392     6
796      6
793      5
        ..
1414     1
1413     1
1410     1
1452     1
1022     1
1021     1
998      1
982      1
983      1
984      1
985      1
1479     1
1477     1
1476     1
993      1
1475     1
1473     1
999      1
1020     1
1001     1
1002     1
1003     1
1005     1
1006     1
1007     1
1463     1
1459     1
1454     1
1019     1
2046     1
Name: TotalBsmtSF, Length: 721, dtype: int64

In [2769]:
train.Heating.value_counts()

GasA     1428
GasW       18
Grav        7
Wall        4
OthW        2
Floor       1
Name: Heating, dtype: int64

In [2770]:
train.HeatingQC.value_counts()

Ex    741
TA    428
Gd    241
Fa     49
Po      1
Name: HeatingQC, dtype: int64

In [2771]:
train.CentralAir.value_counts()

Y    1365
N      95
Name: CentralAir, dtype: int64

In [2772]:
train.Electrical.value_counts()

SBrkr    1334
FuseA      94
FuseF      27
FuseP       3
Mix         1
Name: Electrical, dtype: int64

In [2773]:
train['2ndFlrSF']
zero_count = 0
total_count = 0
for column in train['2ndFlrSF'] :
    if column == 0:
        zero_count += 1
    total_count += 1
print("Zeros in 2ndFlrSF : {}".format(zero_count))
print("Total count 2ndFlrSF : {}".format(total_count))

Zeros in 2ndFlrSF : 829
Total count 2ndFlrSF : 1460

In [2774]:
train.LowQualFinSF.value_counts()

0      1434
80        3
360       2
528       1
53        1
120       1
144       1
156       1
205       1
232       1
234       1
371       1
572       1
390       1
392       1
397       1
420       1
473       1
479       1
481       1
513       1
514       1
515       1
384       1
Name: LowQualFinSF, dtype: int64

In [2775]:
train.GrLivArea.value_counts()

864     22
1040    14
894     11
848     10
1456    10
912      9
1200     9
816      8
1092     8
1344     7
1728     7
987      7
1056     6
1224     6
1768     6
1494     6
1484     6
630      6
1144     5
1314     5
960      5
1252     5
1710     5
1392     5
988      5
990      5
1656     5
1218     5
1302     5
882      4
        ..
1357     1
1347     1
1453     1
1346     1
1343     1
1342     1
1338     1
1334     1
1327     1
1322     1
1385     1
1386     1
1387     1
1391     1
1446     1
3493     1
1436     1
1434     1
1429     1
1425     1
1411     1
1406     1
1405     1
1402     1
1400     1
3447     1
1396     1
1395     1
1393     1
2054     1
Name: GrLivArea, Length: 861, dtype: int64

In [2776]:
train.BsmtFullBath.value_counts()

0    856
1    588
2     15
3      1
Name: BsmtFullBath, dtype: int64

In [2777]:
train.BsmtHalfBath.value_counts()

0    1378
1      80
2       2
Name: BsmtHalfBath, dtype: int64

In [2778]:
train.FullBath.value_counts()

2    768
1    650
3     33
0      9
Name: FullBath, dtype: int64

In [2779]:
train.HalfBath.value_counts()

0    913
1    535
2     12
Name: HalfBath, dtype: int64

In [2780]:
train.BedroomAbvGr.value_counts()

3    804
2    358
4    213
1     50
5     21
6      7
0      6
8      1
Name: BedroomAbvGr, dtype: int64

In [2781]:
train.KitchenAbvGr.value_counts()

1    1392
2      65
3       2
0       1
Name: KitchenAbvGr, dtype: int64

In [2782]:
train.KitchenQual.value_counts()

TA    735
Gd    586
Ex    100
Fa     39
Name: KitchenQual, dtype: int64

In [2783]:
train.TotRmsAbvGrd.value_counts()

6     402
7     329
5     275
8     187
4      97
9      75
10     47
11     18
3      17
12     11
14      1
2       1
Name: TotRmsAbvGrd, dtype: int64

In [2784]:
train.Functional.value_counts()

Typ     1360
Min2      34
Min1      31
Mod       15
Maj1      14
Maj2       5
Sev        1
Name: Functional, dtype: int64

In [2785]:
train.Fireplaces.value_counts()

0    690
1    650
2    115
3      5
Name: Fireplaces, dtype: int64

In [2786]:
train.FireplaceQu.value_counts()

Gd    380
TA    313
Fa     33
Ex     24
Po     20
Name: FireplaceQu, dtype: int64

In [2787]:
train.GarageType.value_counts()

Attchd     870
Detchd     387
BuiltIn     88
Basment     19
CarPort      9
2Types       6
Name: GarageType, dtype: int64

In [2788]:
train.GarageYrBlt.value_counts()

2005.0    65
2006.0    59
2004.0    53
2003.0    50
2007.0    49
1977.0    35
1998.0    31
1999.0    30
2008.0    29
1976.0    29
2000.0    27
2002.0    26
1968.0    26
1950.0    24
1993.0    22
2009.0    21
1965.0    21
1966.0    21
1962.0    21
1958.0    21
2001.0    20
1996.0    20
1957.0    20
1970.0    20
1960.0    19
1997.0    19
1978.0    19
1954.0    19
1974.0    18
1994.0    18
          ..
1922.0     5
1936.0     5
1916.0     5
1931.0     4
1945.0     4
1935.0     4
1928.0     4
1946.0     4
1982.0     4
1938.0     3
1921.0     3
1924.0     3
1910.0     3
1952.0     3
1932.0     3
2010.0     3
1923.0     3
1937.0     2
1934.0     2
1918.0     2
1947.0     2
1929.0     2
1914.0     2
1915.0     2
1942.0     2
1908.0     1
1927.0     1
1933.0     1
1900.0     1
1906.0     1
Name: GarageYrBlt, Length: 97, dtype: int64

In [2789]:
train.GarageFinish.value_counts()

Unf    605
RFn    422
Fin    352
Name: GarageFinish, dtype: int64

In [2790]:
train.GarageCars.value_counts()

2    824
1    369
3    181
0     81
4      5
Name: GarageCars, dtype: int64

In [2791]:
train.GarageArea.value_counts()

0       81
440     49
576     47
240     38
484     34
528     33
288     27
400     25
480     24
264     24
308     20
420     19
280     16
672     15
216     12
504     12
336     12
352     12
360     11
564     11
300     10
462     10
572     10
540     10
539      9
660      9
180      9
384      9
312      9
286      9
        ..
414      1
413      1
768      1
455      1
708      1
757      1
711      1
714      1
481      1
716      1
479      1
719      1
477      1
721      1
475      1
722      1
726      1
732      1
738      1
739      1
740      1
748      1
749      1
752      1
753      1
754      1
459      1
458      1
756      1
1418     1
Name: GarageArea, Length: 441, dtype: int64

In [2792]:
train.GarageQual.value_counts()

TA    1311
Fa      48
Gd      14
Ex       3
Po       3
Name: GarageQual, dtype: int64

In [2793]:
train.GarageCond.value_counts()

TA    1326
Fa      35
Gd       9
Po       7
Ex       2
Name: GarageCond, dtype: int64

In [2794]:
train.PavedDrive.value_counts()

Y    1340
N      90
P      30
Name: PavedDrive, dtype: int64

In [2795]:
train.WoodDeckSF.value_counts()

0      761
192     38
100     36
144     33
120     31
168     28
140     15
224     14
240     10
208     10
216      9
180      8
160      8
250      6
132      6
264      6
143      6
96       6
156      6
171      5
48       5
196      5
105      5
288      5
210      5
220      4
158      4
104      4
147      4
74       4
      ...
183      1
181      1
179      1
245      1
255      1
340      1
304      1
333      1
327      1
326      1
325      1
321      1
312      1
309      1
307      1
306      1
305      1
303      1
257      1
301      1
298      1
295      1
294      1
283      1
278      1
269      1
265      1
263      1
260      1
215      1
Name: WoodDeckSF, Length: 274, dtype: int64

In [2796]:
train.OpenPorchSF.value_counts()

0      656
36      29
48      22
20      21
40      19
45      19
30      16
24      16
60      15
39      14
28      14
44      13
50      13
54      13
72      12
98      11
63      11
35      11
32      11
75      10
42      10
120     10
96      10
64       9
66       9
16       8
78       8
56       8
38       8
84       8
      ...
123      1
523      1
118      1
117      1
106      1
103      1
101      1
95       1
94       1
93       1
134      1
137      1
199      1
141      1
195      1
191      1
189      1
188      1
187      1
185      1
182      1
180      1
176      1
175      1
174      1
159      1
156      1
148      1
142      1
119      1
Name: OpenPorchSF, Length: 202, dtype: int64

In [2797]:
train.EnclosedPorch.value_counts()

0      1252
112      15
96        6
120       5
144       5
192       5
216       5
252       4
116       4
156       4
126       3
228       3
128       3
184       3
102       3
150       3
40        3
176       3
164       3
77        2
185       2
80        2
180       2
84        2
160       2
168       2
205       2
158       2
154       2
100       2
       ...
239       1
242       1
248       1
280       1
254       1
259       1
268       1
198       1
194       1
129       1
148       1
130       1
134       1
136       1
138       1
140       1
143       1
272       1
145       1
386       1
291       1
162       1
169       1
170       1
172       1
174       1
177       1
183       1
189       1
552       1
Name: EnclosedPorch, Length: 120, dtype: int64

In [2798]:
train['3SsnPorch']
total_count = 0
zero_count = 0

for row in train['3SsnPorch'] :
    if row == 0 :
        zero_count += 1
    total_count += 1
    
print("Number of zeros : {}".format(zero_count))
print("Total number of rows : {}".format(total_count))

Number of zeros : 1436
Total number of rows : 1460

In [2799]:
train.ScreenPorch.value_counts()

0      1344
192       6
224       5
120       5
189       4
180       4
160       3
168       3
144       3
126       3
147       3
90        3
200       2
198       2
216       2
184       2
259       2
100       2
176       2
170       2
288       2
142       2
153       1
154       1
152       1
155       1
145       1
156       1
143       1
322       1
       ...
163       1
165       1
291       1
287       1
276       1
273       1
271       1
266       1
265       1
263       1
260       1
252       1
234       1
233       1
225       1
374       1
222       1
220       1
210       1
204       1
197       1
385       1
190       1
396       1
185       1
182       1
440       1
178       1
312       1
480       1
Name: ScreenPorch, Length: 76, dtype: int64

In [2800]:
train.PoolArea.value_counts()

/home/itso/.local/lib/python3.6/site-packages/IPython/core/displayhook.py:271: UserWarning: Output cache limit (currently 1000 entries) hit.
Flushing oldest 200 entries.
  'Flushing oldest {cull_count} entries.'.format(sz=sz, cull_count=cull_count))

0      1453
738       1
648       1
576       1
555       1
519       1
512       1
480       1
Name: PoolArea, dtype: int64

In [2801]:
train.PoolQC.value_counts()

Gd    3
Ex    2
Fa    2
Name: PoolQC, dtype: int64

In [2802]:
train.Fence.value_counts()

MnPrv    157
GdPrv     59
GdWo      54
MnWw      11
Name: Fence, dtype: int64

In [2803]:
train.MiscFeature.value_counts()

Shed    49
Othr     2
Gar2     2
TenC     1
Name: MiscFeature, dtype: int64

In [2804]:
train.MiscVal.value_counts()

0        1408
400        11
500         8
700         5
450         4
2000        4
600         4
1200        2
480         2
1150        1
800         1
15500       1
620         1
3500        1
560         1
2500        1
1300        1
1400        1
350         1
8300        1
54          1
Name: MiscVal, dtype: int64

In [2805]:
train.MoSold.value_counts()

6     253
7     234
5     204
4     141
8     122
3     106
10     89
11     79
9      63
12     59
1      58
2      52
Name: MoSold, dtype: int64

In [2806]:
train.YrSold.value_counts()

2009    338
2007    329
2006    314
2008    304
2010    175
Name: YrSold, dtype: int64

In [2807]:
train.SaleType.value_counts()

WD       1267
New       122
COD        43
ConLD       9
ConLw       5
ConLI       5
CWD         4
Oth         3
Con         2
Name: SaleType, dtype: int64

In [2808]:
train.SaleCondition.value_counts()

Normal     1198
Partial     125
Abnorml     101
Family       20
Alloca       12
AdjLand       4
Name: SaleCondition, dtype: int64

In [2809]:
train

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000
11,20,RL,70.0,11200,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,129500
12,60,RL,85.0,11924,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,7,2006,New,Partial,345000
13,20,RL,NaN,12968,Pave,NaN,IR2,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,144000
14,20,RL,91.0,10652,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2007,New,Partial,279500
15,20,RL,NaN,10920,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,GdWo,NaN,0,5,2008,WD,Normal,157000
16,45,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,Corner,...,0,NaN,GdPrv,NaN,0,7,2007,WD,Normal,132000
17,20,RL,NaN,11241,Pave,NaN,IR1,Lvl,AllPub,CulDSac,...,0,NaN,NaN,Shed,700,3,2010,WD,Normal,149000
18,90,RL,72.0,10791,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,Shed,500,10,2006,WD,Normal,90000
19,20,RL,66.0,13695,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,159000
20,20,RL,70.0,7560,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,5,2009,COD,Abnorml,139000
21,60,RL,101.0,14215,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,11,2006,New,Partial,325300
22,45,RM,57.0,7449,Pave,Grvl,Reg,Bnk,AllPub,Inside,...,0,NaN,GdPrv,NaN,0,6,2007,WD,Normal,139400
23,20,RL,75.0,9742,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,230000
24,120,RM,44.0,4224,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2007,WD,Normal,129900
25,20,RL,NaN,8246,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,5,2010,WD,Normal,154000
26,20,RL,110.0,14230,Pave,NaN,Reg,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,7,2009,WD,Normal,256300
27,20,RL,60.0,7200,Pave,NaN,Reg,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,134800
28,20,RL,98.0,11478,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,306000
29,20,RL,47.0,16321,Pave,NaN,IR1,Lvl,AllPub,CulDSac,...,0,NaN,NaN,NaN,0,12,2006,WD,Normal,207500
30,30,RM,60.0,6324,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,68500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1431,60,RL,60.0,21930,Pave,NaN,IR3,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,7,2006,WD,Normal,192140
1432,120,RL,NaN,4928,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,10,2009,WD,Normal,143750
1433,30,RL,60.0,10800,Pave,Grvl,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,64500
1434,60,RL,93.0,10261,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,186500
1435,20,RL,80.0,17400,Pave,NaN,Reg,Low,AllPub,Inside,...,0,NaN,NaN,NaN,0,5,2006,WD,Normal,160000
1436,20,RL,80.0,8400,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,GdPrv,NaN,0,7,2008,COD,Abnorml,174000
1437,20,RL,60.0,9000,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,GdWo,NaN,0,5,2007,WD,Normal,120500
1438,20,RL,96.0,12444,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,11,2008,New,Partial,394617
1439,20,RM,90.0,7407,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,4,2010,WD,Normal,149700
1440,60,RL,80.0,11584,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,11,2007,WD,Normal,197000
1441,70,RL,79.0,11526,Pave,NaN,IR1,Bnk,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,191000
1442,120,RM,NaN,4426,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,149300
1443,60,FV,85.0,11003,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2009,WD,Normal,310000
1444,30,RL,NaN,8854,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,5,2009,WD,Normal,121000
1445,20,RL,63.0,8500,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,11,2007,WD,Normal,179600
1446,85,RL,70.0,8400,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,129000
1447,20,RL,NaN,26142,Pave,NaN,IR1,Lvl,AllPub,CulDSac,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,157900
1448,60,RL,80.0,10000,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,12,2007,WD,Normal,240000
1449,50,RL,70.0,11767,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,GdWo,NaN,0,5,2007,WD,Normal,112000
1450,180,RM,21.0,1533,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2006,WD,Abnorml,92000
1451,90,RL,60.0,9000,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,9,2009,WD,Normal,136000
1452,20,RL,78.0,9262,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,5,2009,New,Partial,287090
1453,180,RM,35.0,3675,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,5,2006,WD,Normal,145000
1454,20,RL,90.0,17217,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,7,2006,WD,Abnorml,84500
1455,20,FV,62.0,7500,Pave,Pave,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,10,2009,WD,Normal,185000
1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

After one hot encoding the numeric data and combining it with the one hot encoded  
categorical data I discovered that the algorithm is overfitting.  
So I experimented a bit and discovered that removing the following columns gives the best result

In [2810]:
train = train.drop(['PoolArea', 'MiscVal', 'GarageFinish','FireplaceQu', 'LotConfig', 'LandContour', 'LandSlope' ], axis=1)

In [2811]:
train = train.drop(['Street', 'Utilities', 'PoolQC', 'Fence', 'MiscFeature'], axis=1)

In [2812]:
categorical_column_names = train.dtypes[train.dtypes == 'object'].index
print(categorical_column_names)

Index(['MSZoning', 'Alley', 'LotShape', 'Neighborhood', 'Condition1',
       'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl',
       'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond',
       'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1',
       'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical',
       'KitchenQual', 'Functional', 'GarageType', 'GarageQual', 'GarageCond',
       'PavedDrive', 'SaleType', 'SaleCondition'],
      dtype='object')

In [2813]:
from sklearn.preprocessing import LabelEncoder

In [2814]:
target = train.SalePrice
print(train.shape)
train = train.drop(['SalePrice'], axis=1)
print(train.shape)

(1460, 68)
(1460, 67)

In [2815]:
from sklearn.preprocessing import OneHotEncoder

In [2816]:
numeric_categorical_column_names = ['MSSubClass', 'OverallQual', 'OverallCond', 'MoSold', 'YrSold', 'Fireplaces', 'BedroomAbvGr' ]
numeric_column_names = train.describe().columns
print(numeric_categorical_column_names)
print(numeric_column_names)

['MSSubClass', 'OverallQual', 'OverallCond', 'MoSold', 'YrSold', 'Fireplaces', 'BedroomAbvGr']
Index(['MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond',
       'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2',
       'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces',
       'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'MoSold', 'YrSold'],
      dtype='object')

In [2817]:
def get_categorical_numeric_columns(data, column_names):
    return pd.DataFrame({col: data[col] for col in column_names}, 
                        index = data.index)

numeric_categorical_columns = get_categorical_numeric_columns(train, numeric_categorical_column_names)
numeric_categorical_columns
one_hot_encoder = OneHotEncoder().fit(numeric_categorical_columns)
one_hot_encoded_numeric_categorical = one_hot_encoder.transform(numeric_categorical_columns)
one_hot_encoded_numeric_categorical.todense()

/home/itso/.local/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)

matrix([[0., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]])

In [2818]:
def delete_and_concatenate_one_hot_encoded_columns(data, encoded_numeric_columns, column_names):
    data = data.fillna(0)
    data = data.drop(column_names, axis=1)
    return pd.np.concatenate([encoded_numeric_columns.todense(), data], axis=1)
one_hot_encoded_numeric_columns = delete_and_concatenate_one_hot_encoded_columns(train[numeric_column_names], one_hot_encoded_numeric_categorical, numeric_categorical_column_names)
one_hot_encoded_numeric_columns.shape

(1460, 90)

In [2819]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2820]:
numeric_x_train, numeric_x_test, numeric_y_train, numeric_y_test = train_test_split(one_hot_encoded_numeric_columns, target, test_size=0.3, random_state=4330)

In [2821]:
regressor = LinearRegression().fit(numeric_x_train, numeric_y_train)
print("Train score: {}".format(regressor.score(numeric_x_train, numeric_y_train)))
print("Test score: {}".format(regressor.score(numeric_x_test, numeric_y_test)))

Train score: 0.846556864223003
Test score: 0.8747847104014962

In [2822]:
train = train.fillna("")
encoders = {col: LabelEncoder().fit(train[col]) for col in categorical_column_names}
encoders

{'MSZoning': LabelEncoder(),
 'Alley': LabelEncoder(),
 'LotShape': LabelEncoder(),
 'Neighborhood': LabelEncoder(),
 'Condition1': LabelEncoder(),
 'Condition2': LabelEncoder(),
 'BldgType': LabelEncoder(),
 'HouseStyle': LabelEncoder(),
 'RoofStyle': LabelEncoder(),
 'RoofMatl': LabelEncoder(),
 'Exterior1st': LabelEncoder(),
 'Exterior2nd': LabelEncoder(),
 'MasVnrType': LabelEncoder(),
 'ExterQual': LabelEncoder(),
 'ExterCond': LabelEncoder(),
 'Foundation': LabelEncoder(),
 'BsmtQual': LabelEncoder(),
 'BsmtCond': LabelEncoder(),
 'BsmtExposure': LabelEncoder(),
 'BsmtFinType1': LabelEncoder(),
 'BsmtFinType2': LabelEncoder(),
 'Heating': LabelEncoder(),
 'HeatingQC': LabelEncoder(),
 'CentralAir': LabelEncoder(),
 'Electrical': LabelEncoder(),
 'KitchenQual': LabelEncoder(),
 'Functional': LabelEncoder(),
 'GarageType': LabelEncoder(),
 'GarageQual': LabelEncoder(),
 'GarageCond': LabelEncoder(),
 'PavedDrive': LabelEncoder(),
 'SaleType': LabelEncoder(),
 'SaleCondition': LabelEncoder()}

In [2823]:
def encode_categorical_data(data, columns, encoders):
    return pd.DataFrame({col: encoders[col].transform(data[col]) for col in columns},
                        index = data.index)

train_encoded = encode_categorical_data(train, categorical_column_names, encoders)
train_encoded

,MSZoning,Alley,LotShape,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,RoofStyle,RoofMatl,...,CentralAir,Electrical,KitchenQual,Functional,GarageType,GarageQual,GarageCond,PavedDrive,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1,3,0,3,5,2,2,0,5,1,1,...,1,5,2,6,2,5,5,2,8,4
2,3,0,3,24,1,2,0,2,1,1,...,1,5,3,6,2,5,5,2,8,4
3,3,0,0,5,2,2,0,5,1,1,...,1,5,2,6,2,5,5,2,8,4
4,3,0,0,6,2,2,0,5,1,1,...,1,5,2,6,6,5,5,2,8,0
5,3,0,0,15,2,2,0,5,1,1,...,1,5,2,6,2,5,5,2,8,4
6,3,0,0,11,2,2,0,0,1,1,...,1,5,3,6,2,5,5,2,8,4
7,3,0,3,21,2,2,0,2,1,1,...,1,5,2,6,2,5,5,2,8,4
8,3,0,0,14,4,2,0,5,1,1,...,1,5,3,6,2,5,5,2,8,4
9,4,0,3,17,0,2,0,0,1,1,...,1,2,3,2,6,2,5,2,8,0
10,3,0,3,3,0,0,1,1,1,1,...,1,5,3,6,2,3,5,2,8,4
11,3,0,3,19,2,2,0,2,3,1,...,1,5,3,6,6,5,5,2,8,4
12,3,0,0,16,2,2,0,5,3,1,...,1,5,0,6,4,5,5,2,6,5
13,3,0,1,19,2,2,0,2,3,1,...,1,5,3,6,6,5,5,2,8,4
14,3,0,0,5,2,2,0,2,1,1,...,1,5,2,6,2,5,5,2,6,5
15,3,0,0,12,2,2,0,2,3,1,...,1,5,3,6,2,5,5,2,8,4
16,4,0,3,3,2,2,0,1,1,1,...,1,1,3,6,6,5,5,2,8,4
17,3,0,0,12,2,2,0,2,1,1,...,1,5,3,6,2,5,5,2,8,4
18,3,0,3,19,2,2,2,2,1,1,...,1,5,3,6,5,5,5,2,8,4
19,3,0,3,20,5,2,0,2,1,1,...,1,5,2,6,6,5,5,2,8,4
20,3,0,3,12,2,2,0,2,3,1,...,1,5,3,2,2,5,5,2,0,0
21,3,0,0,16,2,2,0,5,1,1,...,1,5,2,6,4,5,5,2,6,5
22,4,1,3,9,2,2,0,1,1,1,...,1,2,2,6,2,5,5,0,8,4
23,3,0,3,5,2,2,0,2,3,1,...,1,5,2,6,2,5,5,2,8,4
24,4,0,3,10,2,2,4,2,1,1,...,1,5,3,6,2,5,5,2,8,4
25,3,0,0,19,2,2,0,2,1,1,...,1,5,2,6,2,5,5,2,8,4
26,3,0,3,16,2,2,0,2,1,1,...,1,5,2,6,2,5,5,2,8,4
27,3,0,3,12,2,2,0,2,1,1,...,1,5,2,6,6,5,5,2,8,4
28,3,0,3,16,2,2,0,2,1,1,...,1,5,2,6,2,5,5,2,8,4
29,3,0,0,12,2,2,0,2,1,1,...,1,5,3,6,2,5,5,2,8,4
30,4,0,0,3,1,7,0,2,1,1,...,0,5,1,6,6,2,5,2,8,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1431,3,0,2,8,6,2,0,5,1,1,...,1,5,3,6,4,5,5,2,8,4
1432,3,0,0,13,2,2,4,2,1,1,...,1,5,3,6,2,5,5,2,8,4
1433,3,1,3,17,2,2,0,2,1,1,...,1,5,3,6,6,2,2,2,8,4
1434,3,0,0,8,2,2,0,5,1,1,...,1,5,3,6,2,5,5,2,8,4
1435,3,0,3,11,2,2,0,2,1,1,...,1,5,3,6,2,5,5,1,8,4
1436,3,0,3,12,2,2,0,2,1,1,...,1,5,2,6,2,5,5,2,0,0
1437,3,0,3,12,2,2,0,2,1,1,...,1,5,3,6,6,5,5,2,8,4
1438,3,0,3,16,2,2,0,2,3,1,...,1,5,0,6,2,5,5,2,6,5
1439,4,0,3,17,0,2,0,2,1,1,...,1,1,3,6,2,5,5,2,8,4
1440,3,0,3,14,2,2,0,7,3,1,...,1,5,3,6,2,5,5,2,8,4
1441,3,0,0,6,2,2,0,3,1,1,...,1,5,3,2,6,5,5,2,8,4
1442,4,0,3,5,2,2,4,2,1,1,...,1,5,2,6,2,5,5,2,8,4
1443,1,0,3,21,2,2,0,5,1,1,...,1,5,0,6,2,5,5,2,8,4
1444,3,0,3,3,2,2,0,1,1,1,...,0,2,1,6,6,2,4,1,8,4
1445,3,0,3,5,2,2,0,2,1,1,...,1,5,2,6,2,5,5,2,8,4
1446,3,0,3,19,2,2,0,6,1,1,...,1,5,3,6,6,5,5,2,8,4
1447,3,0,0,11,2,2,0,2,1,1,...,1,5,3,6,2,5,5,1,8,4
1448,3,0,3,5,2,2,0,5,1,1,...,1,5,2,6,2,5,5,2,8,4
1449,3,0,3,7,2,2,0,5,1,1,...,0,5,3,3,6,2,5,2,8,4
1450,4,0,3,10,2,2,3,6,1,1,...,1,5,0,6,0,0,0,2,8,0
1451,3,0,3,12,2,2,2,5,1,1,...,1,5,3,6,0,0,0,2,8,4
1452,3,0,3,21,2,2,0,2,1,1,...,1,5,0,6,2,5,5,2,6,5
1453,4,0,3,7,2,2,4,7,1,1,...,1,5,3,6,3,5,5,2,8,4
1454,3,0,3,11,2,2,0,2,1,1,...,1,5,3,6,0,0,0,2,8,0
1455,1,2,3,21,2,2,0,2,1,1,...,1,5,2,6,2,5,5,2,8,4
1456,3,0,3,8,2,2,0,5,1,1,...,1,5,3,6,2,5,5,2,8,4
1457,3,0,3,14,2,2,0,2,1,1,...,1,5,3,2,2,5,5,2,8,4
1458,3,0,3,6,2,2,0,5,1,1,...,1,5,2,6,2,5,5,2,8,4
1459,3,0,3,12,2,2,0,2,3,1,...,1,1,2,6,2,5,5,2,8,4
1460,3,0,3,7,2,2,0,2,1,1,...,1,5,3,6,2,5,5,2,8,4

In [2824]:
one_hot_encoder = OneHotEncoder().fit(train_encoded)
one_hot_train = one_hot_encoder.transform(train_encoded)
one_hot_train[:8].todense()

/home/itso/.local/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)

matrix([[0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        ...,
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.]])

In [2825]:
categorical_x_train, categorical_x_test, categorical_y_train, categorical_y_test = train_test_split(one_hot_train, target, test_size=0.3, random_state=4330)

In [2826]:
cat_regression = LinearRegression().fit(categorical_x_train, categorical_y_train)
print("Train score: {}".format(cat_regression.score(categorical_x_train, categorical_y_train)))
print("Test score: {}".format(cat_regression.score(categorical_x_test, categorical_y_test)))

Train score: 0.8436438337805736
Test score: 0.7809467194607604

In [2827]:
new_x_train = pd.np.concatenate([categorical_x_train.todense(), numeric_x_train], axis=1)
new_x_test = pd.np.concatenate([categorical_x_test.todense(), numeric_x_test], axis=1)
print(new_x_train.shape, new_x_test.shape)

(1022, 318) (438, 318)

In [2828]:
all_data_lr = LinearRegression().fit(new_x_train, numeric_y_train)
print(all_data_lr.score(new_x_train, numeric_y_train))
print(all_data_lr.score(new_x_test, numeric_y_test))

0.9349471934053946
-4823341325.447794

The algorithm seems to be overfitting. We need to add Regularisation

In [2829]:
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso

alpha = [0.01, 0.1, 1, 10, 100, 110, 120]

for a in alpha:
    all_data_lr = Ridge(alpha = a).fit(new_x_train, numeric_y_train)
    print('alpha:', a)
    print(all_data_lr.score(new_x_train, numeric_y_train), all_data_lr.score(new_x_test, numeric_y_test))
    print()

alpha: 0.01
0.9349284440312967 0.8918832773945596

alpha: 0.1
0.933646748205652 0.8985564679824424

alpha: 1
0.9193638462077796 0.9023800849370462

alpha: 10
0.8932189829927127 0.8968969673209001

alpha: 100
0.8453638895624581 0.872090630528122

alpha: 110
0.8424745483505622 0.870133828169777

alpha: 120
0.8397693514645856 0.8682835499094899

In [2830]:
alpha = [0.01, 0.1, 1, 10, 100, 110, 120]

for a in alpha:
    all_data_lr = Lasso(alpha = a).fit(new_x_train, numeric_y_train)
    print('alpha:', a)
    print(all_data_lr.score(new_x_train, numeric_y_train), all_data_lr.score(new_x_test, numeric_y_test))
    print()

/home/itso/.local/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)

alpha: 0.01
0.9349200786000048 0.9020164885120849

/home/itso/.local/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)

alpha: 0.1
0.9349196211314427 0.9032789175011129

/home/itso/.local/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)

alpha: 1
0.93488445149926 0.9068184357849973

alpha: 10
0.9335002899205024 0.9141124316280268

alpha: 100
0.9176213138073992 0.9229489751409118

alpha: 110
0.9158770314569912 0.922136239223644

alpha: 120
0.9140429111325177 0.9211905437091982

In [2831]:
alphas = [0.01, 0.1, 1, 10, 100, 1000]
for alpha in alphas:
    all_data_lr = Ridge(alpha = alpha).fit(new_x_train, pd.np.log10(numeric_y_train))
    print('alpha:', alpha)
    print(all_data_lr.score(new_x_train, pd.np.log10(numeric_y_train)), all_data_lr.score(new_x_test, pd.np.log10(numeric_y_test)))
    print()

alpha: 0.01
0.9442482958534169 0.9041126372624133

alpha: 0.1
0.943495443912984 0.9102743578982686

alpha: 1
0.9354479975438232 0.917128432140833

alpha: 10
0.9173170150221515 0.9210077868703075

alpha: 100
0.8755845569681387 0.9063910257854224

alpha: 1000
0.8065833951935986 0.8698019250260921

In [2832]:
alphas = [0.01, 0.1, 1, 10, 100, 1000]
for alpha in alphas:
    all_data_lr = Lasso(alpha = alpha).fit(new_x_train, pd.np.log10(numeric_y_train))
    print('alpha:', alpha)
    print(all_data_lr.score(new_x_train, pd.np.log10(numeric_y_train)), all_data_lr.score(new_x_test, pd.np.log10(numeric_y_test)))
    print()

alpha: 0.01
0.7670965376207838 0.848096274199668

alpha: 0.1
0.7648589576331366 0.8508372596609324

alpha: 1
0.6892447734367962 0.8047894022682348

alpha: 10
0.5605707854446249 0.6860374796904143

alpha: 100
0.05557879428799606 0.06272177853007221

alpha: 1000
0.0 -0.0007908082127179307

Not a good idea

In [2833]:
from sklearn.metrics import r2_score

for alpha in [0.0001, .001,0.01, 0.1, 1, 10, 100]:
    all_data_lr = Ridge(alpha = alpha).fit(new_x_train, pd.np.log10(numeric_y_train))
    print('alpha:', alpha)
    print(r2_score(10**all_data_lr.predict(new_x_train), numeric_y_train))
    print(r2_score(10**all_data_lr.predict(new_x_test), numeric_y_test))
    print()

alpha: 0.0001
0.9402360998256263
0.9333760510332423

alpha: 0.001
0.9402142896057419
0.9334124939091957

alpha: 0.01
0.9399871830008175
0.9337374981972

alpha: 0.1
0.9372569542096063
0.9346125492407036

alpha: 1
0.9175337443511119
0.9226362191917957

alpha: 10
0.874323162173244
0.9020110044800486

alpha: 100
0.7496460013979038
0.8423653081011502

Best:  
Train score: 0.9357610536886232  
Test score: 0.9337198674221399  
alpha = 10